### ISSUE TITLE
Flows stopped as the credentials could not be decrypted

### ISSUE THREAD

**Issue by stepic** [guidone/redbot-alexa-sandbox#1]
Cannot import project because of this error:

"Flows stopped as the credentials could not be decrypted.

The flow credential file is encrypted, but the project's encryption key is missing or invalid."

**Comment by guidone** [comment]
Ok @stepic I've removed the credentials from the flow and fixed a bug in the configuration (install redbot 0.16.3) that I believe is the problem that was causing your 404 in ngrok

Thanks for the feedback!
